# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.6

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /Applications/CLion.app/Contents/bin/cmake/bin/cmake

# The command to remove a file.
RM = /Applications/CLion.app/Contents/bin/cmake/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/dwuziu/Projects/blackbird

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/dwuziu/Projects/blackbird

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/Applications/CLion.app/Contents/bin/cmake/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/Applications/CLion.app/Contents/bin/cmake/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/dwuziu/Projects/blackbird/CMakeFiles /Users/dwuziu/Projects/blackbird/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/dwuziu/Projects/blackbird/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named blackbird

# Build rule for target.
blackbird: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 blackbird
.PHONY : blackbird

# fast build rule for target.
blackbird/fast:
	$(MAKE) -f CMakeFiles/blackbird.dir/build.make CMakeFiles/blackbird.dir/build
.PHONY : blackbird/fast

src/bitcoin.o: src/bitcoin.cpp.o

.PHONY : src/bitcoin.o

# target to build an object file
src/bitcoin.cpp.o:
	$(MAKE) -f CMakeFiles/blackbird.dir/build.make CMakeFiles/blackbird.dir/src/bitcoin.cpp.o
.PHONY : src/bitcoin.cpp.o

src/bitcoin.i: src/bitcoin.cpp.i

.PHONY : src/bitcoin.i

# target to preprocess a source file
src/bitcoin.cpp.i:
	$(MAKE) -f CMakeFiles/blackbird.dir/build.make CMakeFiles/blackbird.dir/src/bitcoin.cpp.i
.PHONY : src/bitcoin.cpp.i

src/bitcoin.s: src/bitcoin.cpp.s

.PHONY : src/bitcoin.s

# target to generate assembly for a file
src/bitcoin.cpp.s:
	$(MAKE) -f CMakeFiles/blackbird.dir/build.make CMakeFiles/blackbird.dir/src/bitcoin.cpp.s
.PHONY : src/bitcoin.cpp.s

src/check_entry_exit.o: src/check_entry_exit.cpp.o

.PHONY : src/check_entry_exit.o

# target to build an object file
src/check_entry_exit.cpp.o:
	$(MAKE) -f CMakeFiles/blackbird.dir/build.make CMakeFiles/blackbird.dir/src/check_entry_exit.cpp.o
.PHONY : src/check_entry_exit.cpp.o

src/check_entry_exit.i: src/check_entry_exit.cpp.i

.PHONY : src/check_entry_exit.i

# target to preprocess a source file
src/check_entry_exit.cpp.i:
	$(MAKE) -f CMakeFiles/blackbird.dir/build.make CMakeFiles/blackbird.dir/src/check_entry_exit.cpp.i
.PHONY : src/check_entry_exit.cpp.i

src/check_entry_exit.s: src/check_entry_exit.cpp.s

.PHONY : src/check_entry_exit.s

# target to generate assembly for a file
src/check_entry_exit.cpp.s:
	$(MAKE) -f CMakeFiles/blackbird.dir/build.make CMakeFiles/blackbird.dir/src/check_entry_exit.cpp.s
.PHONY : src/check_entry_exit.cpp.s

src/curl_fun.o: src/curl_fun.cpp.o

.PHONY : src/curl_fun.o

# target to build an object file
src/curl_fun.cpp.o:
	$(MAKE) -f CMakeFiles/blackbird.dir/build.make CMakeFiles/blackbird.dir/src/curl_fun.cpp.o
.PHONY : src/curl_fun.cpp.o

src/curl_fun.i: src/curl_fun.cpp.i

.PHONY : src/curl_fun.i

# target to preprocess a source file
src/curl_fun.cpp.i:
	$(MAKE) -f CMakeFiles/blackbird.dir/build.make CMakeFiles/blackbird.dir/src/curl_fun.cpp.i
.PHONY : src/curl_fun.cpp.i

src/curl_fun.s: src/curl_fun.cpp.s

.PHONY : src/curl_fun.s

# target to generate assembly for a file
src/curl_fun.cpp.s:
	$(MAKE) -f CMakeFiles/blackbird.dir/build.make CMakeFiles/blackbird.dir/src/curl_fun.cpp.s
.PHONY : src/curl_fun.cpp.s

src/db_fun.o: src/db_fun.cpp.o

.PHONY : src/db_fun.o

# target to build an object file
src/db_fun.cpp.o:
	$(MAKE) -f CMakeFiles/blackbird.dir/build.make CMakeFiles/blackbird.dir/src/db_fun.cpp.o
.PHONY : src/db_fun.cpp.o

src/db_fun.i: src/db_fun.cpp.i

.PHONY : src/db_fun.i

# target to preprocess a source file
src/db_fun.cpp.i:
	$(MAKE) -f CMakeFiles/blackbird.dir/build.make CMakeFiles/blackbird.dir/src/db_fun.cpp.i
.PHONY : src/db_fun.cpp.i

src/db_fun.s: src/db_fun.cpp.s

.PHONY : src/db_fun.s

# target to generate assembly for a file
src/db_fun.cpp.s:
	$(MAKE) -f CMakeFiles/blackbird.dir/build.make CMakeFiles/blackbird.dir/src/db_fun.cpp.s
.PHONY : src/db_fun.cpp.s

src/exchange/bitfinex.o: src/exchange/bitfinex.cpp.o

.PHONY : src/exchange/bitfinex.o

# target to build an object file
src/exchange/bitfinex.cpp.o:
	$(MAKE) -f CMakeFiles/blackbird.dir/build.make CMakeFiles/blackbird.dir/src/exchange/bitfinex.cpp.o
.PHONY : src/exchange/bitfinex.cpp.o

src/exchange/bitfinex.i: src/exchange/bitfinex.cpp.i

.PHONY : src/exchange/bitfinex.i

# target to preprocess a source file
src/exchange/bitfinex.cpp.i:
	$(MAKE) -f CMakeFiles/blackbird.dir/build.make CMakeFiles/blackbird.dir/src/exchange/bitfinex.cpp.i
.PHONY : src/exchange/bitfinex.cpp.i

src/exchange/bitfinex.s: src/exchange/bitfinex.cpp.s

.PHONY : src/exchange/bitfinex.s

# target to generate assembly for a file
src/exchange/bitfinex.cpp.s:
	$(MAKE) -f CMakeFiles/blackbird.dir/build.make CMakeFiles/blackbird.dir/src/exchange/bitfinex.cpp.s
.PHONY : src/exchange/bitfinex.cpp.s

src/exchange/bitstamp.o: src/exchange/bitstamp.cpp.o

.PHONY : src/exchange/bitstamp.o

# target to build an object file
src/exchange/bitstamp.cpp.o:
	$(MAKE) -f CMakeFiles/blackbird.dir/build.make CMakeFiles/blackbird.dir/src/exchange/bitstamp.cpp.o
.PHONY : src/exchange/bitstamp.cpp.o

src/exchange/bitstamp.i: src/exchange/bitstamp.cpp.i

.PHONY : src/exchange/bitstamp.i

# target to preprocess a source file
src/exchange/bitstamp.cpp.i:
	$(MAKE) -f CMakeFiles/blackbird.dir/build.make CMakeFiles/blackbird.dir/src/exchange/bitstamp.cpp.i
.PHONY : src/exchange/bitstamp.cpp.i

src/exchange/bitstamp.s: src/exchange/bitstamp.cpp.s

.PHONY : src/exchange/bitstamp.s

# target to generate assembly for a file
src/exchange/bitstamp.cpp.s:
	$(MAKE) -f CMakeFiles/blackbird.dir/build.make CMakeFiles/blackbird.dir/src/exchange/bitstamp.cpp.s
.PHONY : src/exchange/bitstamp.cpp.s

src/exchange/btce.o: src/exchange/btce.cpp.o

.PHONY : src/exchange/btce.o

# target to build an object file
src/exchange/btce.cpp.o:
	$(MAKE) -f CMakeFiles/blackbird.dir/build.make CMakeFiles/blackbird.dir/src/exchange/btce.cpp.o
.PHONY : src/exchange/btce.cpp.o

src/exchange/btce.i: src/exchange/btce.cpp.i

.PHONY : src/exchange/btce.i

# target to preprocess a source file
src/exchange/btce.cpp.i:
	$(MAKE) -f CMakeFiles/blackbird.dir/build.make CMakeFiles/blackbird.dir/src/exchange/btce.cpp.i
.PHONY : src/exchange/btce.cpp.i

src/exchange/btce.s: src/exchange/btce.cpp.s

.PHONY : src/exchange/btce.s

# target to generate assembly for a file
src/exchange/btce.cpp.s:
	$(MAKE) -f CMakeFiles/blackbird.dir/build.make CMakeFiles/blackbird.dir/src/exchange/btce.cpp.s
.PHONY : src/exchange/btce.cpp.s

src/exchange/gemini.o: src/exchange/gemini.cpp.o

.PHONY : src/exchange/gemini.o

# target to build an object file
src/exchange/gemini.cpp.o:
	$(MAKE) -f CMakeFiles/blackbird.dir/build.make CMakeFiles/blackbird.dir/src/exchange/gemini.cpp.o
.PHONY : src/exchange/gemini.cpp.o

src/exchange/gemini.i: src/exchange/gemini.cpp.i

.PHONY : src/exchange/gemini.i

# target to preprocess a source file
src/exchange/gemini.cpp.i:
	$(MAKE) -f CMakeFiles/blackbird.dir/build.make CMakeFiles/blackbird.dir/src/exchange/gemini.cpp.i
.PHONY : src/exchange/gemini.cpp.i

src/exchange/gemini.s: src/exchange/gemini.cpp.s

.PHONY : src/exchange/gemini.s

# target to generate assembly for a file
src/exchange/gemini.cpp.s:
	$(MAKE) -f CMakeFiles/blackbird.dir/build.make CMakeFiles/blackbird.dir/src/exchange/gemini.cpp.s
.PHONY : src/exchange/gemini.cpp.s

src/exchange/itbit.o: src/exchange/itbit.cpp.o

.PHONY : src/exchange/itbit.o

# target to build an object file
src/exchange/itbit.cpp.o:
	$(MAKE) -f CMakeFiles/blackbird.dir/build.make CMakeFiles/blackbird.dir/src/exchange/itbit.cpp.o
.PHONY : src/exchange/itbit.cpp.o

src/exchange/itbit.i: src/exchange/itbit.cpp.i

.PHONY : src/exchange/itbit.i

# target to preprocess a source file
src/exchange/itbit.cpp.i:
	$(MAKE) -f CMakeFiles/blackbird.dir/build.make CMakeFiles/blackbird.dir/src/exchange/itbit.cpp.i
.PHONY : src/exchange/itbit.cpp.i

src/exchange/itbit.s: src/exchange/itbit.cpp.s

.PHONY : src/exchange/itbit.s

# target to generate assembly for a file
src/exchange/itbit.cpp.s:
	$(MAKE) -f CMakeFiles/blackbird.dir/build.make CMakeFiles/blackbird.dir/src/exchange/itbit.cpp.s
.PHONY : src/exchange/itbit.cpp.s

src/exchange/kraken.o: src/exchange/kraken.cpp.o

.PHONY : src/exchange/kraken.o

# target to build an object file
src/exchange/kraken.cpp.o:
	$(MAKE) -f CMakeFiles/blackbird.dir/build.make CMakeFiles/blackbird.dir/src/exchange/kraken.cpp.o
.PHONY : src/exchange/kraken.cpp.o

src/exchange/kraken.i: src/exchange/kraken.cpp.i

.PHONY : src/exchange/kraken.i

# target to preprocess a source file
src/exchange/kraken.cpp.i:
	$(MAKE) -f CMakeFiles/blackbird.dir/build.make CMakeFiles/blackbird.dir/src/exchange/kraken.cpp.i
.PHONY : src/exchange/kraken.cpp.i

src/exchange/kraken.s: src/exchange/kraken.cpp.s

.PHONY : src/exchange/kraken.s

# target to generate assembly for a file
src/exchange/kraken.cpp.s:
	$(MAKE) -f CMakeFiles/blackbird.dir/build.make CMakeFiles/blackbird.dir/src/exchange/kraken.cpp.s
.PHONY : src/exchange/kraken.cpp.s

src/exchange/okcoin.o: src/exchange/okcoin.cpp.o

.PHONY : src/exchange/okcoin.o

# target to build an object file
src/exchange/okcoin.cpp.o:
	$(MAKE) -f CMakeFiles/blackbird.dir/build.make CMakeFiles/blackbird.dir/src/exchange/okcoin.cpp.o
.PHONY : src/exchange/okcoin.cpp.o

src/exchange/okcoin.i: src/exchange/okcoin.cpp.i

.PHONY : src/exchange/okcoin.i

# target to preprocess a source file
src/exchange/okcoin.cpp.i:
	$(MAKE) -f CMakeFiles/blackbird.dir/build.make CMakeFiles/blackbird.dir/src/exchange/okcoin.cpp.i
.PHONY : src/exchange/okcoin.cpp.i

src/exchange/okcoin.s: src/exchange/okcoin.cpp.s

.PHONY : src/exchange/okcoin.s

# target to generate assembly for a file
src/exchange/okcoin.cpp.s:
	$(MAKE) -f CMakeFiles/blackbird.dir/build.make CMakeFiles/blackbird.dir/src/exchange/okcoin.cpp.s
.PHONY : src/exchange/okcoin.cpp.s

src/exchange/poloniex.o: src/exchange/poloniex.cpp.o

.PHONY : src/exchange/poloniex.o

# target to build an object file
src/exchange/poloniex.cpp.o:
	$(MAKE) -f CMakeFiles/blackbird.dir/build.make CMakeFiles/blackbird.dir/src/exchange/poloniex.cpp.o
.PHONY : src/exchange/poloniex.cpp.o

src/exchange/poloniex.i: src/exchange/poloniex.cpp.i

.PHONY : src/exchange/poloniex.i

# target to preprocess a source file
src/exchange/poloniex.cpp.i:
	$(MAKE) -f CMakeFiles/blackbird.dir/build.make CMakeFiles/blackbird.dir/src/exchange/poloniex.cpp.i
.PHONY : src/exchange/poloniex.cpp.i

src/exchange/poloniex.s: src/exchange/poloniex.cpp.s

.PHONY : src/exchange/poloniex.s

# target to generate assembly for a file
src/exchange/poloniex.cpp.s:
	$(MAKE) -f CMakeFiles/blackbird.dir/build.make CMakeFiles/blackbird.dir/src/exchange/poloniex.cpp.s
.PHONY : src/exchange/poloniex.cpp.s

src/main.o: src/main.cpp.o

.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) -f CMakeFiles/blackbird.dir/build.make CMakeFiles/blackbird.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i

.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) -f CMakeFiles/blackbird.dir/build.make CMakeFiles/blackbird.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s

.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) -f CMakeFiles/blackbird.dir/build.make CMakeFiles/blackbird.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/parameters.o: src/parameters.cpp.o

.PHONY : src/parameters.o

# target to build an object file
src/parameters.cpp.o:
	$(MAKE) -f CMakeFiles/blackbird.dir/build.make CMakeFiles/blackbird.dir/src/parameters.cpp.o
.PHONY : src/parameters.cpp.o

src/parameters.i: src/parameters.cpp.i

.PHONY : src/parameters.i

# target to preprocess a source file
src/parameters.cpp.i:
	$(MAKE) -f CMakeFiles/blackbird.dir/build.make CMakeFiles/blackbird.dir/src/parameters.cpp.i
.PHONY : src/parameters.cpp.i

src/parameters.s: src/parameters.cpp.s

.PHONY : src/parameters.s

# target to generate assembly for a file
src/parameters.cpp.s:
	$(MAKE) -f CMakeFiles/blackbird.dir/build.make CMakeFiles/blackbird.dir/src/parameters.cpp.s
.PHONY : src/parameters.cpp.s

src/result.o: src/result.cpp.o

.PHONY : src/result.o

# target to build an object file
src/result.cpp.o:
	$(MAKE) -f CMakeFiles/blackbird.dir/build.make CMakeFiles/blackbird.dir/src/result.cpp.o
.PHONY : src/result.cpp.o

src/result.i: src/result.cpp.i

.PHONY : src/result.i

# target to preprocess a source file
src/result.cpp.i:
	$(MAKE) -f CMakeFiles/blackbird.dir/build.make CMakeFiles/blackbird.dir/src/result.cpp.i
.PHONY : src/result.cpp.i

src/result.s: src/result.cpp.s

.PHONY : src/result.s

# target to generate assembly for a file
src/result.cpp.s:
	$(MAKE) -f CMakeFiles/blackbird.dir/build.make CMakeFiles/blackbird.dir/src/result.cpp.s
.PHONY : src/result.cpp.s

src/time_fun.o: src/time_fun.cpp.o

.PHONY : src/time_fun.o

# target to build an object file
src/time_fun.cpp.o:
	$(MAKE) -f CMakeFiles/blackbird.dir/build.make CMakeFiles/blackbird.dir/src/time_fun.cpp.o
.PHONY : src/time_fun.cpp.o

src/time_fun.i: src/time_fun.cpp.i

.PHONY : src/time_fun.i

# target to preprocess a source file
src/time_fun.cpp.i:
	$(MAKE) -f CMakeFiles/blackbird.dir/build.make CMakeFiles/blackbird.dir/src/time_fun.cpp.i
.PHONY : src/time_fun.cpp.i

src/time_fun.s: src/time_fun.cpp.s

.PHONY : src/time_fun.s

# target to generate assembly for a file
src/time_fun.cpp.s:
	$(MAKE) -f CMakeFiles/blackbird.dir/build.make CMakeFiles/blackbird.dir/src/time_fun.cpp.s
.PHONY : src/time_fun.cpp.s

src/utils/base64.o: src/utils/base64.cpp.o

.PHONY : src/utils/base64.o

# target to build an object file
src/utils/base64.cpp.o:
	$(MAKE) -f CMakeFiles/blackbird.dir/build.make CMakeFiles/blackbird.dir/src/utils/base64.cpp.o
.PHONY : src/utils/base64.cpp.o

src/utils/base64.i: src/utils/base64.cpp.i

.PHONY : src/utils/base64.i

# target to preprocess a source file
src/utils/base64.cpp.i:
	$(MAKE) -f CMakeFiles/blackbird.dir/build.make CMakeFiles/blackbird.dir/src/utils/base64.cpp.i
.PHONY : src/utils/base64.cpp.i

src/utils/base64.s: src/utils/base64.cpp.s

.PHONY : src/utils/base64.s

# target to generate assembly for a file
src/utils/base64.cpp.s:
	$(MAKE) -f CMakeFiles/blackbird.dir/build.make CMakeFiles/blackbird.dir/src/utils/base64.cpp.s
.PHONY : src/utils/base64.cpp.s

src/utils/send_email.o: src/utils/send_email.cpp.o

.PHONY : src/utils/send_email.o

# target to build an object file
src/utils/send_email.cpp.o:
	$(MAKE) -f CMakeFiles/blackbird.dir/build.make CMakeFiles/blackbird.dir/src/utils/send_email.cpp.o
.PHONY : src/utils/send_email.cpp.o

src/utils/send_email.i: src/utils/send_email.cpp.i

.PHONY : src/utils/send_email.i

# target to preprocess a source file
src/utils/send_email.cpp.i:
	$(MAKE) -f CMakeFiles/blackbird.dir/build.make CMakeFiles/blackbird.dir/src/utils/send_email.cpp.i
.PHONY : src/utils/send_email.cpp.i

src/utils/send_email.s: src/utils/send_email.cpp.s

.PHONY : src/utils/send_email.s

# target to generate assembly for a file
src/utils/send_email.cpp.s:
	$(MAKE) -f CMakeFiles/blackbird.dir/build.make CMakeFiles/blackbird.dir/src/utils/send_email.cpp.s
.PHONY : src/utils/send_email.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... blackbird"
	@echo "... src/bitcoin.o"
	@echo "... src/bitcoin.i"
	@echo "... src/bitcoin.s"
	@echo "... src/check_entry_exit.o"
	@echo "... src/check_entry_exit.i"
	@echo "... src/check_entry_exit.s"
	@echo "... src/curl_fun.o"
	@echo "... src/curl_fun.i"
	@echo "... src/curl_fun.s"
	@echo "... src/db_fun.o"
	@echo "... src/db_fun.i"
	@echo "... src/db_fun.s"
	@echo "... src/exchange/bitfinex.o"
	@echo "... src/exchange/bitfinex.i"
	@echo "... src/exchange/bitfinex.s"
	@echo "... src/exchange/bitstamp.o"
	@echo "... src/exchange/bitstamp.i"
	@echo "... src/exchange/bitstamp.s"
	@echo "... src/exchange/btce.o"
	@echo "... src/exchange/btce.i"
	@echo "... src/exchange/btce.s"
	@echo "... src/exchange/gemini.o"
	@echo "... src/exchange/gemini.i"
	@echo "... src/exchange/gemini.s"
	@echo "... src/exchange/itbit.o"
	@echo "... src/exchange/itbit.i"
	@echo "... src/exchange/itbit.s"
	@echo "... src/exchange/kraken.o"
	@echo "... src/exchange/kraken.i"
	@echo "... src/exchange/kraken.s"
	@echo "... src/exchange/okcoin.o"
	@echo "... src/exchange/okcoin.i"
	@echo "... src/exchange/okcoin.s"
	@echo "... src/exchange/poloniex.o"
	@echo "... src/exchange/poloniex.i"
	@echo "... src/exchange/poloniex.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/parameters.o"
	@echo "... src/parameters.i"
	@echo "... src/parameters.s"
	@echo "... src/result.o"
	@echo "... src/result.i"
	@echo "... src/result.s"
	@echo "... src/time_fun.o"
	@echo "... src/time_fun.i"
	@echo "... src/time_fun.s"
	@echo "... src/utils/base64.o"
	@echo "... src/utils/base64.i"
	@echo "... src/utils/base64.s"
	@echo "... src/utils/send_email.o"
	@echo "... src/utils/send_email.i"
	@echo "... src/utils/send_email.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

